awsAccountId: "{{ .Env.AWS_ACCOUNT_ID }}"
backend:
  image: "{{ .Env.AWS_ACCOUNT_ID }}.dkr.ecr.{{ .Env.AWS_REGION }}.amazonaws.com/monitor/repo:backend-{{ .Chart.Version }}"
  replicas: 2
  port: 8080

frontend:
  image: "{{ .Env.AWS_ACCOUNT_ID }}.dkr.ecr.{{ .Env.AWS_REGION }}.amazonaws.com/monitor/repo:frontend-{{ .Chart.Version }}"
  replicas: 2
  port: 80

ingress:
  enabled: true
  host: "frontend.example.com"
  path: "/"
