apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountId }}:role/kube-monitor-irsa-test
